apiVersion: kubevirt.io/v1
kind: VirtualMachine
metadata:
  name: web-01
  labels:
    app.kubernetes.io/name: web-01
    app.kubernetes.io/part-of: gitops-vms
    app.kubernetes.io/managed-by: gitops
    vm-role: web
spec:
  runStrategy: Always
  dataVolumeTemplates:
    - metadata:
        name: web-01-rootdisk
      spec:
        sourceRef:
          kind: DataSource
          name: fedora
          namespace: openshift-virtualization-os-images
        storage:
          resources:
            requests:
              storage: 30Gi
  template:
    metadata:
      labels:
        kubevirt.io/domain: web-01
        app.kubernetes.io/name: web-01
        vm-role: web
    spec:
      evictionStrategy: LiveMigrate
      domain:
        cpu:
          cores: 2
        memory:
          guest: 4Gi
        devices:
          disks:
            - name: rootdisk
              disk:
                bus: virtio
            - name: cloudinit
              disk:
                bus: virtio
          interfaces:
            - name: default
              masquerade: {}
      networks:
        - name: default
          pod: {}
      volumes:
        - name: rootdisk
          dataVolume:
            name: web-01-rootdisk
        - name: cloudinit
          cloudInitNoCloud:
            userData: |
              #cloud-config
              hostname: web-01
              users:
                - name: cloud-user
                  sudo: ALL=(ALL) NOPASSWD:ALL
                  ssh_authorized_keys:
                    - ssh-ed25519 TODO_REPLACE_WITH_YOUR_PUBLIC_KEY
